apiVersion: v1
version: 6.4.1
appVersion: 6.4.1
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- http://localhost:5000/v2/stefanprodan/podinfo
kubeVersion: ">=1.23.0-0"
